name: 'lakehouse'
version: '1.0.0'
config-version: 2

profile: 'lakehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "INSTALL httpfs; LOAD httpfs;"
  - "INSTALL aws; LOAD aws;"
  - "SET s3_endpoint='minio:9000';"
  - "SET s3_use_ssl=false;"
  - "SET s3_url_style='path';"
  - "CALL load_aws_credentials();"

models:
  lakehouse:
    materialized: external
    format: delta
    raw:
      materialized: table
    silver:
      materialized: external
      format: delta
    gold:
      materialized: external
      format: delta
