name: 'tu_proyecto_dbt'
version: '1.0.0'
config-version: 2

profile: 'tu_proyecto_dbt'

# --- AGREGA ESTE BLOQUE ---
on-run-start:
  - "INSTALL httpfs;"
  - "LOAD httpfs;"
  - "INSTALL ducklake;"
  - "LOAD ducklake;"
  - "CREATE SECRET IF NOT EXISTS minio_secret (TYPE S3, KEY_ID 'admin', SECRET 'password123', REGION 'us-east-1', ENDPOINT 'minio:9000', URL_STYLE 'path', USE_SSL false);"
# --------------------------

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  tu_proyecto_dbt:
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold