# Archivo: /workspace/dbt_project/dbt_project.yml
name: 'lakehouse'
version: '1.0.0'
config-version: 2
profile: 'mi_pos_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# 👇 CONFIGURACIÓN DE LA ARQUITECTURA MEDALLÓN
models:
  lakehouse:
    +database: my_lake # Forzamos a que todo viva en tu DuckLake
    
    silver:
      +schema: silver
      +materialized: view # Silver suele ser vistas ligeras o tablas incrementales
      
    gold:
      +schema: gold
      +materialized: table # Gold siempre son tablas sólidas listas para consultar