lakehouse:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /tmp/lakehouse.duckdb
      extensions:
        - httpfs
        - aws
        - delta  # Agregamos la extensión delta aquí para lectura nativa

      secrets:
        - type: s3
          region: "{{ env_var('AWS_REGION', 'us-east-1') }}"
          endpoint: "minio:9000"
          key_id: "{{ env_var('AWS_ACCESS_KEY_ID', 'admin') }}"
          secret: "{{ env_var('AWS_SECRET_ACCESS_KEY', 'password123') }}"
          use_ssl: false
          url_style: "path"

    prod:
      type: duckdb
      path: /tmp/lakehouse_prod.duckdb
      extensions:
        - httpfs
        - aws
        - delta
      plugins:
        - module: delta
      secrets:
        - type: s3
          region: "{{ env_var('AWS_REGION', 'us-east-1') }}"
          endpoint: "minio:9000"
          key_id: "{{ env_var('AWS_ACCESS_KEY_ID', 'admin') }}"
          secret: "{{ env_var('AWS_SECRET_ACCESS_KEY', 'password123') }}"
          use_ssl: false
          url_style: "path"