# Archivo: /workspace/dbt_project/profiles.yml
mi_pos_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'local_dbt.duckdb'
      extensions:
        - httpfs
        - ducklake