FROM apache/airflow:2.9.1-python3.10
USER root
RUN apt-get update && apt-get install -y \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
USER airflow
RUN pip install --no-cache-dir \
    duckdb==1.5.2 \
    dbt-core==1.11.8 \
    dbt-duckdb==1.10.1 \
    pandas==2.2.2 \
    deltalake==0.17.0 \
    boto3==1.34.100